sudo: required

services:
  - docker

before_install:
  - docker build -t davidsells/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -t davidsells/react-test npm test -- --coverage

after_success:
  - docker build -t davidsells/multi-client ./client
  - docker build -t davidsells/multi-nginx ./nginx
  - docker build -t davidsells/multi-server ./server
  - docker build -t davidsells/multi-worker ./worker
    #- echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker push davidsells/multi-client
  - docker push davidsells/multi-nginx
  - docker push davidsells/multi-server
  - docker push davidsells/multi-worker
          

